### ISSUE TITLE
error building

### ISSUE THREAD

**Issue by nsubuga** [suyashkumar/ssl-proxy#13]
when type go get or build i get this error : ./main.go:105:16: m.TLSConfig undefined (type *autocert.Manager has no field or method TLSConfig) please help resolve thanks

**Comment by suyashkumar** [comment]
hi @nsubuga! Did you attempt to build by running `make`? This will use [`dep`](https://github.com/golang/dep) to fetch the right versions of the dependencies based on `Gopkg.lock` (in this case the right version of `golang.org/x/crypto` is needed). Also are you using a version of Go >= 1.10 ? Note you also need to have [`dep`](https://github.com/golang/dep) installed.

The API for `autocert` may have changed recently, which I can take a look at. Building this using the instructions in the README (using `make` and the included `Makefile`) should work--let me know if it still doesn't. I'll probably include a docker configuration to make builds even easier soon as well.

**Comment by suyashkumar** [comment]
@nsubuga any updates? If not I'll go ahead and close this issue out soon!

**Comment by suyashkumar** [comment]
Builds seem to work fine when testing locally, and I've now also provided Docker configurations to reproducibly build across platforms in #14! Closing this out.
