### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by codingsett** [suyashkumar/ssl-proxy#19]
I used this proxy before and everything was working like a charm...now when i come back to run it doesnt work.

This is my webserver..
![image](https://user-images.githubusercontent.com/27306293/70862024-ad5e5100-1f47-11ea-9239-6d726486dc88.png)

This is the ssl proxy running

![image](https://user-images.githubusercontent.com/27306293/70862049-fe6e4500-1f47-11ea-8b68-46004e15a55f.png)

What i get when i go to http://api.codingsett.codes
![image](https://user-images.githubusercontent.com/27306293/70862064-44c3a400-1f48-11ea-8f16-7835d687f205.png)

**Comment by codingsett** [comment]
additionally this is what i get 

```
Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```

**Comment by suyashkumar** [comment]
Hi there! It looks like this requires ssl-proxy to be build against a recent fix in the Go crypto libraries: https://github.com/golang/crypto/commit/0e8c3a9068a2fb325459490d2ce7baa4ffe2d00f includes the update. 

If you pull down the latest golang/crypto and re-build your ssl-proxy binary everything should work, and sometime today I can release a binary built with this latest crypto fix included. Thanks!

**Comment by codingsett** [comment]
Thanks for the reply did that and it worked!
