### ISSUE TITLE
acme/autocert: missing server name

### ISSUE THREAD

**Issue by 1722393429** [suyashkumar/ssl-proxy#36]
2022/03/02 20:26:18 http: TLS handshake error from 138.246.253.24:41988: acme/autocert: missing server name

**Comment by tcwalther** [comment]
While this issue has little information about the problem, I can confirm that letsencrypt integration seems to be broken. It used to work flawlessly less than a year ago, but when I run ssl-proxy with `-domain=example.com` now, I get the same error message. Using a manual cert+key pair (created via `certbot`) works fine.

**Comment by suyashkumar** [comment]
Thanks for reporting this folks! I'll take a look at this this weekend. Out of curiosity, does this happen with the prebuilt binaries and also when you build from source?

**Comment by grischard** [comment]
Hi! This happens to me when I build from source.

**Comment by suyashkumar** [comment]
Thanks folks! I think that I've been able to repro and fix the error in a limited test environment, simply by updating the golang crypto dependencies. Sending a PR here: https://github.com/suyashkumar/ssl-proxy/pull/37 that should be merged soon. Thanks for reporting, and if you get a chance to test it let me know if it worked in your usage. Thanks!

**Comment by suyashkumar** [comment]
This should be addressed with #37, and I've also published an updated release with prebuilt binaries here: https://github.com/suyashkumar/ssl-proxy/releases/tag/v0.2.7

Give them a try and let me know if you still have issues. Thanks!

**Comment by Jipok** [comment]
Fixed for me.

**Comment by suyashkumar** [comment]
Great! I'll close this out then. If anyone else has similar issues feel free to comment and reopen. Thanks!

**Comment by mxbfnk** [comment]
Heyja, I think the problem is present again with newest version 0.5.2.

Connecting from WIN Agent to Linux Proxy. 

-selfcert works fine!

**Comment by grischard** [comment]
@mxbfnk Since this issue is two years old and the original cause of that problem got resolved, can I suggest opening a new issue?

**Comment by mxbfnk** [comment]
sure. ;) I thought here because of the last comment from @suyashkumar
