### ISSUE TITLE
acme/autocert: missing server name

### ISSUE THREAD

**Issue by diogovalentte** [suyashkumar/ssl-proxy#45]
I've the same issue of that issue https://github.com/suyashkumar/ssl-proxy/issues/36, and i'm trying using the last version of ssl-proxy-linux-amd64 realese 0.2.7 and building from source with last commit 09cb9a.

The ssl-proxy was running fine, then i stopped, and when i started ssl-proxy again, show that error.

Using my cert and key works fine.

**Comment by suyashkumar** [comment]
thanks for reporting! Last time, this was fixed with updating the golang crypto dependencies (I have a PR open for that here that you can try: #46). If that doesn't work I'll take a closer look this week!

**Comment by diogovalentte** [comment]
> thanks for reporting! Last time, this was fixed with updating the golang crypto dependencies (I have a PR open for that here that you can try: #46). If that doesn't work I'll take a closer look this week!

It worked, thanks!
