### ISSUE TITLE
Unable to install https://getbin.io dead?

### ISSUE THREAD

**Issue by connected201** [suyashkumar/ssl-proxy#47]
hi, i unable to install because domain https://getbin.io seems to be dead!.

**Comment by suyashkumar** [comment]
Hi there! you can always install by downloading from the GitHub releases tab, but I've gotten getbin.io back up (thanks for letting me know)!

At some point will try to setup getbin to be serverless which will help. Thanks!

**Comment by connected201** [comment]
yes, i installed with downloading archive from release page.
